### ISSUE TITLE
Contributors guide

### ISSUE THREAD

**Issue by emcniece** [dan-divy/spruce#58]
Hello! I'd like to start contributing, but I have some questions about project guidelines. Would you be interested in establishing a `CONTRIBUTING` file?

What is a contributors guide? https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors

Some examples (extracted from the link above):

- [Atom editor](https://github.com/atom/atom/blob/master/CONTRIBUTING.md)
- [Ruby on Rails](https://github.com/rails/rails/blob/master/CONTRIBUTING.md)
- [Open Government](https://github.com/opengovernment/opengovernment/blob/master/CONTRIBUTING.md)

Some questions I have:

- What kind of branching method do you prefer?
- How do you prefer pull request content - squashed, or with atomic commits?
- Does this project follow a code styleguide?
- Does this project have any linting or unit tests that need to pass?
  - If yes, how much coverage is acceptable?
- How are releases planned and created?

Are you interested in establishing guidelines like this? Would you prefer to do it collaboratively, or solo?

**Comment by dan-online** [comment]
Hi @emcniece! Thank you for your interest in this project. Here are some answers I can provide:

- What kind of branching method do you prefer?

You can fork this project and create a pull request. At the moment branch "project-oak" is where I would recommend making any new contributions.

- How do you prefer pull request content - squashed, or with atomic commits?

Either is completely fine for us!

- Does this project follow a code styleguide?

We ask you to keep your code tidy but I will format it if needed. 

- Does this project have any linting or unit tests that need to pass?

``npm test`` contains some database tests but I usually personally test any pull request. Along with this we will submit a review to the pull request for any changes etc..

- How are releases planned and created?

project-oak is due to be merged into master soon as v2 which will occur after some more testing and finishing the app it comes with.

---
I would love to create some contribution guidelines, if you include a basic template in a pull request Ill add as necessary. 

Thanks

Dan

**Comment by dan-online** [comment]
Closing as this has been answered
